spring:
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: upvote-service
          uri: http://localhost:8080
          predicates:
            - Path=/upvote/**
        - id: comment-service
          uri: http://localhost:8083
          predicates:
            - Path=/comments/**
        - id: article-service
          uri: http://localhost:8081
          predicates:
            - Path=/articles/**
        - id: SECUTIRY-SERVICE
          uri: lb://SECURITY-SERVICE
          predicates:
            - Path=/oauth/** 
        - id: LOGIN-SERVICE
          uri: lb://LOGIN-SERVICE
          predicates:
            - Path=/login/**        