spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/users/**
        - id: upvote-service
          uri: http://localhost:8080
          predicates:
            - Path=/upvote/**
        - id: comment-service
          uri: http://localhost:8083
          predicates:
            - Path=/comments/**
        - id: article-service
          uri: http://localhost:8081
          predicates:
            - Path=/articles/**